// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChOFwmB7MGEj2y2BGc7-KhZT3XV20M3BI',
    appId: '1:469928265687:web:782c166086e6416fc42d92',
    messagingSenderId: '469928265687',
    projectId: 'todoapp-da69e',
    authDomain: 'todoapp-da69e.firebaseapp.com',
    storageBucket: 'todoapp-da69e.appspot.com',
    measurementId: 'G-57B2E919MV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPSHa3lrlm1pGZ0__Vf-ucYCDvKVTTa-k',
    appId: '1:469928265687:android:8d34c6340e82da27c42d92',
    messagingSenderId: '469928265687',
    projectId: 'todoapp-da69e',
    storageBucket: 'todoapp-da69e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaYBC7yZTdBFEjigz2R5Xbs5k9D9rCrqY',
    appId: '1:469928265687:ios:2688636bf0c3b51dc42d92',
    messagingSenderId: '469928265687',
    projectId: 'todoapp-da69e',
    storageBucket: 'todoapp-da69e.appspot.com',
    iosBundleId: 'com.example.todoGextApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaYBC7yZTdBFEjigz2R5Xbs5k9D9rCrqY',
    appId: '1:469928265687:ios:5f343b003f5f25dcc42d92',
    messagingSenderId: '469928265687',
    projectId: 'todoapp-da69e',
    storageBucket: 'todoapp-da69e.appspot.com',
    iosBundleId: 'com.example.todoGextApp.RunnerTests',
  );
}
